---
- name: Setup target machine
  become: false
  hosts: all
  vars:
    #
    # -- required --
    #
    remote_folder: "{{ remote_folder }}"
    # e.g. trazo
    project_name: "{{ project_name }}"
    # e.g. develop
    project_stage: "{{ project_stage }}"
    #
    # -- generated --
    #
    db_host_name: "{{ project_name }}-db-{{ project_stage }}"
    db_name: "{{ project_stage }}-db-{{ project_stage }}"
    db_username: "app_user_{{ project_stage }}"

  tasks:
    - name: Ensure target directory exists
      file:
        path: "{{ remote_folder }}"
        state: directory
        mode: '0755'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

