import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";

import { Providers } from "@/providers/providers";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className={`relative ${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          {children}
          <Toaster
            richColors
            position="top-center"
            toastOptions={{
              style: {
                background: "#fff",
                borderBlockColor: "#e2e8f0",
              },
            }}
            closeButton
          />
        </Providers>
      </body>
    </html>
  );
}
